server:
  port: 8004
spring:
  application:
    name: springcloud-demo-config-server
  cloud:
    config:
      server:
        git:
          # https://github.com/dengxyt/springcloud-configserver/blob/master/src/main/resources/application-user.yml
          uri: https://github.com/dengxyt/springcloud-configserver
          username: dengxyt
          password: orochi4653