server:
  port: 8004
spring:
  application:
    name: springcloud-demo-config-server
  cloud:
    config:
      server:
        git:
          # 通过 http://localhost:8004/application/user 进行访问
          uri: https://github.com/dengxyt/springcloud-configserver
          username: dengxyt
          password: orochi4653
#logging:
#  level:
#    org.springframework.cloud: DEBUG
#    org.springframework.boot: DEBUG