server:
  port: 8004
spring:
  application:
    name: springcloud-demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo
          username: 
          password: 